// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"

	"github.com/go-faster/errors"
)

func (s *ErrRespStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type CreateNewOrderBadRequest struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *CreateNewOrderBadRequest) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *CreateNewOrderBadRequest) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *CreateNewOrderBadRequest) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *CreateNewOrderBadRequest) SetMessage(val string) {
	s.Message = val
}

func (*CreateNewOrderBadRequest) createNewOrderRes() {}

type CreateNewOrderCreated struct {
	// Uuid of the current order.
	OrderUUID string `json:"order_uuid"`
	// Total price of the current order.
	TotalPrice float32 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateNewOrderCreated) GetOrderUUID() string {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateNewOrderCreated) GetTotalPrice() float32 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateNewOrderCreated) SetOrderUUID(val string) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateNewOrderCreated) SetTotalPrice(val float32) {
	s.TotalPrice = val
}

func (*CreateNewOrderCreated) createNewOrderRes() {}

type CreateNewOrderForbidden struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *CreateNewOrderForbidden) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *CreateNewOrderForbidden) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *CreateNewOrderForbidden) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *CreateNewOrderForbidden) SetMessage(val string) {
	s.Message = val
}

func (*CreateNewOrderForbidden) createNewOrderRes() {}

type CreateNewOrderInternalServerError struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *CreateNewOrderInternalServerError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *CreateNewOrderInternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *CreateNewOrderInternalServerError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *CreateNewOrderInternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*CreateNewOrderInternalServerError) createNewOrderRes() {}

type CreateNewOrderReq struct {
	// User uuid.
	UserUUID string `json:"user_uuid"`
	// Uuid of the detail(-s).
	PartUuids []string `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateNewOrderReq) GetUserUUID() string {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateNewOrderReq) GetPartUuids() []string {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateNewOrderReq) SetUserUUID(val string) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateNewOrderReq) SetPartUuids(val []string) {
	s.PartUuids = val
}

type CreateNewOrderUnprocessableEntity struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *CreateNewOrderUnprocessableEntity) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *CreateNewOrderUnprocessableEntity) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *CreateNewOrderUnprocessableEntity) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *CreateNewOrderUnprocessableEntity) SetMessage(val string) {
	s.Message = val
}

func (*CreateNewOrderUnprocessableEntity) createNewOrderRes() {}

type ErrResp struct {
	// HTTP-code error.
	Code OptInt `json:"code"`
	// Error description.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *ErrResp) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ErrResp) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ErrResp) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ErrResp) SetMessage(val OptString) {
	s.Message = val
}

// ErrRespStatusCode wraps ErrResp with StatusCode.
type ErrRespStatusCode struct {
	StatusCode int
	Response   ErrResp
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrRespStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrRespStatusCode) GetResponse() ErrResp {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrRespStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrRespStatusCode) SetResponse(val ErrResp) {
	s.Response = val
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptOrderByUUIDOKPaymentMethod returns new OptOrderByUUIDOKPaymentMethod with value set to v.
func NewOptOrderByUUIDOKPaymentMethod(v OrderByUUIDOKPaymentMethod) OptOrderByUUIDOKPaymentMethod {
	return OptOrderByUUIDOKPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptOrderByUUIDOKPaymentMethod is optional OrderByUUIDOKPaymentMethod.
type OptOrderByUUIDOKPaymentMethod struct {
	Value OrderByUUIDOKPaymentMethod
	Set   bool
}

// IsSet returns true if OptOrderByUUIDOKPaymentMethod was set.
func (o OptOrderByUUIDOKPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOrderByUUIDOKPaymentMethod) Reset() {
	var v OrderByUUIDOKPaymentMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOrderByUUIDOKPaymentMethod) SetTo(v OrderByUUIDOKPaymentMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOrderByUUIDOKPaymentMethod) Get() (v OrderByUUIDOKPaymentMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOrderByUUIDOKPaymentMethod) Or(d OrderByUUIDOKPaymentMethod) OrderByUUIDOKPaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptOrderByUUIDOKStatus returns new OptOrderByUUIDOKStatus with value set to v.
func NewOptOrderByUUIDOKStatus(v OrderByUUIDOKStatus) OptOrderByUUIDOKStatus {
	return OptOrderByUUIDOKStatus{
		Value: v,
		Set:   true,
	}
}

// OptOrderByUUIDOKStatus is optional OrderByUUIDOKStatus.
type OptOrderByUUIDOKStatus struct {
	Value OrderByUUIDOKStatus
	Set   bool
}

// IsSet returns true if OptOrderByUUIDOKStatus was set.
func (o OptOrderByUUIDOKStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOrderByUUIDOKStatus) Reset() {
	var v OrderByUUIDOKStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOrderByUUIDOKStatus) SetTo(v OrderByUUIDOKStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOrderByUUIDOKStatus) Get() (v OrderByUUIDOKStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOrderByUUIDOKStatus) Or(d OrderByUUIDOKStatus) OrderByUUIDOKStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type OrderByUUIDNotFound struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *OrderByUUIDNotFound) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *OrderByUUIDNotFound) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *OrderByUUIDNotFound) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *OrderByUUIDNotFound) SetMessage(val string) {
	s.Message = val
}

func (*OrderByUUIDNotFound) orderByUUIDRes() {}

type OrderByUUIDOK struct {
	// Order uuid.
	OrderUUID OptString `json:"order_uuid"`
	// User uuid.
	UserUUID OptString `json:"user_uuid"`
	// Uuid of the detail(-s).
	PartUuids []string `json:"part_uuids"`
	// Total price of the order.
	TotalPrice OptFloat64 `json:"total_price"`
	// Transaction uuid.
	TransactionUUID OptString `json:"transaction_uuid"`
	// Payment method of the order.
	PaymentMethod OptOrderByUUIDOKPaymentMethod `json:"payment_method"`
	// Order payment status.
	Status OptOrderByUUIDOKStatus `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *OrderByUUIDOK) GetOrderUUID() OptString {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *OrderByUUIDOK) GetUserUUID() OptString {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *OrderByUUIDOK) GetPartUuids() []string {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *OrderByUUIDOK) GetTotalPrice() OptFloat64 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *OrderByUUIDOK) GetTransactionUUID() OptString {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *OrderByUUIDOK) GetPaymentMethod() OptOrderByUUIDOKPaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *OrderByUUIDOK) GetStatus() OptOrderByUUIDOKStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *OrderByUUIDOK) SetOrderUUID(val OptString) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *OrderByUUIDOK) SetUserUUID(val OptString) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *OrderByUUIDOK) SetPartUuids(val []string) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *OrderByUUIDOK) SetTotalPrice(val OptFloat64) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *OrderByUUIDOK) SetTransactionUUID(val OptString) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *OrderByUUIDOK) SetPaymentMethod(val OptOrderByUUIDOKPaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *OrderByUUIDOK) SetStatus(val OptOrderByUUIDOKStatus) {
	s.Status = val
}

func (*OrderByUUIDOK) orderByUUIDRes() {}

// Payment method of the order.
type OrderByUUIDOKPaymentMethod string

const (
	OrderByUUIDOKPaymentMethodUNKNOWN  OrderByUUIDOKPaymentMethod = "UNKNOWN"
	OrderByUUIDOKPaymentMethodCARD     OrderByUUIDOKPaymentMethod = "CARD"
	OrderByUUIDOKPaymentMethodSBP      OrderByUUIDOKPaymentMethod = "SBP"
	OrderByUUIDOKPaymentMethodTRANSFER OrderByUUIDOKPaymentMethod = "TRANSFER"
)

// AllValues returns all OrderByUUIDOKPaymentMethod values.
func (OrderByUUIDOKPaymentMethod) AllValues() []OrderByUUIDOKPaymentMethod {
	return []OrderByUUIDOKPaymentMethod{
		OrderByUUIDOKPaymentMethodUNKNOWN,
		OrderByUUIDOKPaymentMethodCARD,
		OrderByUUIDOKPaymentMethodSBP,
		OrderByUUIDOKPaymentMethodTRANSFER,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderByUUIDOKPaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case OrderByUUIDOKPaymentMethodUNKNOWN:
		return []byte(s), nil
	case OrderByUUIDOKPaymentMethodCARD:
		return []byte(s), nil
	case OrderByUUIDOKPaymentMethodSBP:
		return []byte(s), nil
	case OrderByUUIDOKPaymentMethodTRANSFER:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderByUUIDOKPaymentMethod) UnmarshalText(data []byte) error {
	switch OrderByUUIDOKPaymentMethod(data) {
	case OrderByUUIDOKPaymentMethodUNKNOWN:
		*s = OrderByUUIDOKPaymentMethodUNKNOWN
		return nil
	case OrderByUUIDOKPaymentMethodCARD:
		*s = OrderByUUIDOKPaymentMethodCARD
		return nil
	case OrderByUUIDOKPaymentMethodSBP:
		*s = OrderByUUIDOKPaymentMethodSBP
		return nil
	case OrderByUUIDOKPaymentMethodTRANSFER:
		*s = OrderByUUIDOKPaymentMethodTRANSFER
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Order payment status.
type OrderByUUIDOKStatus string

const (
	OrderByUUIDOKStatusPANDINGPAYMENT OrderByUUIDOKStatus = "PANDING_PAYMENT"
	OrderByUUIDOKStatusPAID           OrderByUUIDOKStatus = "PAID"
	OrderByUUIDOKStatusCANCELLED      OrderByUUIDOKStatus = "CANCELLED"
)

// AllValues returns all OrderByUUIDOKStatus values.
func (OrderByUUIDOKStatus) AllValues() []OrderByUUIDOKStatus {
	return []OrderByUUIDOKStatus{
		OrderByUUIDOKStatusPANDINGPAYMENT,
		OrderByUUIDOKStatusPAID,
		OrderByUUIDOKStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderByUUIDOKStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderByUUIDOKStatusPANDINGPAYMENT:
		return []byte(s), nil
	case OrderByUUIDOKStatusPAID:
		return []byte(s), nil
	case OrderByUUIDOKStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderByUUIDOKStatus) UnmarshalText(data []byte) error {
	switch OrderByUUIDOKStatus(data) {
	case OrderByUUIDOKStatusPANDINGPAYMENT:
		*s = OrderByUUIDOKStatusPANDINGPAYMENT
		return nil
	case OrderByUUIDOKStatusPAID:
		*s = OrderByUUIDOKStatusPAID
		return nil
	case OrderByUUIDOKStatusCANCELLED:
		*s = OrderByUUIDOKStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type OrderCancelConflict struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *OrderCancelConflict) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *OrderCancelConflict) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *OrderCancelConflict) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *OrderCancelConflict) SetMessage(val string) {
	s.Message = val
}

func (*OrderCancelConflict) orderCancelRes() {}

// OrderCancelNoContent is response for OrderCancel operation.
type OrderCancelNoContent struct{}

func (*OrderCancelNoContent) orderCancelRes() {}

type OrderCancelNotFound struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *OrderCancelNotFound) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *OrderCancelNotFound) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *OrderCancelNotFound) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *OrderCancelNotFound) SetMessage(val string) {
	s.Message = val
}

func (*OrderCancelNotFound) orderCancelRes() {}

type OrderPaymentBadRequest struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *OrderPaymentBadRequest) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *OrderPaymentBadRequest) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *OrderPaymentBadRequest) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *OrderPaymentBadRequest) SetMessage(val string) {
	s.Message = val
}

func (*OrderPaymentBadRequest) orderPaymentRes() {}

type OrderPaymentForbidden struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *OrderPaymentForbidden) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *OrderPaymentForbidden) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *OrderPaymentForbidden) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *OrderPaymentForbidden) SetMessage(val string) {
	s.Message = val
}

func (*OrderPaymentForbidden) orderPaymentRes() {}

type OrderPaymentInternalServerError struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *OrderPaymentInternalServerError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *OrderPaymentInternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *OrderPaymentInternalServerError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *OrderPaymentInternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*OrderPaymentInternalServerError) orderPaymentRes() {}

type OrderPaymentNotFound struct {
	// HTTP-code error.
	Code int `json:"code"`
	// Error description.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *OrderPaymentNotFound) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *OrderPaymentNotFound) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *OrderPaymentNotFound) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *OrderPaymentNotFound) SetMessage(val string) {
	s.Message = val
}

func (*OrderPaymentNotFound) orderPaymentRes() {}

type OrderPaymentOK struct {
	// Uuid of current transaction.
	TransactionUUID string `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *OrderPaymentOK) GetTransactionUUID() string {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *OrderPaymentOK) SetTransactionUUID(val string) {
	s.TransactionUUID = val
}

func (*OrderPaymentOK) orderPaymentRes() {}

type OrderPaymentReq struct {
	// Payment method of the order.
	PaymentMethod OrderPaymentReqPaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *OrderPaymentReq) GetPaymentMethod() OrderPaymentReqPaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *OrderPaymentReq) SetPaymentMethod(val OrderPaymentReqPaymentMethod) {
	s.PaymentMethod = val
}

// Payment method of the order.
type OrderPaymentReqPaymentMethod string

const (
	OrderPaymentReqPaymentMethodUNKNOWN  OrderPaymentReqPaymentMethod = "UNKNOWN"
	OrderPaymentReqPaymentMethodCARD     OrderPaymentReqPaymentMethod = "CARD"
	OrderPaymentReqPaymentMethodSBP      OrderPaymentReqPaymentMethod = "SBP"
	OrderPaymentReqPaymentMethodTRANSFER OrderPaymentReqPaymentMethod = "TRANSFER"
)

// AllValues returns all OrderPaymentReqPaymentMethod values.
func (OrderPaymentReqPaymentMethod) AllValues() []OrderPaymentReqPaymentMethod {
	return []OrderPaymentReqPaymentMethod{
		OrderPaymentReqPaymentMethodUNKNOWN,
		OrderPaymentReqPaymentMethodCARD,
		OrderPaymentReqPaymentMethodSBP,
		OrderPaymentReqPaymentMethodTRANSFER,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderPaymentReqPaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case OrderPaymentReqPaymentMethodUNKNOWN:
		return []byte(s), nil
	case OrderPaymentReqPaymentMethodCARD:
		return []byte(s), nil
	case OrderPaymentReqPaymentMethodSBP:
		return []byte(s), nil
	case OrderPaymentReqPaymentMethodTRANSFER:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderPaymentReqPaymentMethod) UnmarshalText(data []byte) error {
	switch OrderPaymentReqPaymentMethod(data) {
	case OrderPaymentReqPaymentMethodUNKNOWN:
		*s = OrderPaymentReqPaymentMethodUNKNOWN
		return nil
	case OrderPaymentReqPaymentMethodCARD:
		*s = OrderPaymentReqPaymentMethodCARD
		return nil
	case OrderPaymentReqPaymentMethodSBP:
		*s = OrderPaymentReqPaymentMethodSBP
		return nil
	case OrderPaymentReqPaymentMethodTRANSFER:
		*s = OrderPaymentReqPaymentMethodTRANSFER
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
