// Code generated by ogen, DO NOT EDIT.
package api

type CreateNewOrderRes interface {
	createNewOrderRes()
}

type OrderByUUIDRes interface {
	orderByUUIDRes()
}

type OrderCancelRes interface {
	orderCancelRes()
}

type OrderPaymentRes interface {
	orderPaymentRes()
}
