// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateNewOrderOperation OperationName = "CreateNewOrder"
	OrderByUUIDOperation    OperationName = "OrderByUUID"
	OrderCancelOperation    OperationName = "OrderCancel"
	OrderPaymentOperation   OperationName = "OrderPayment"
)
