// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateNewOrder implements CreateNewOrder operation.
	//
	// Create a new order with selected details.
	//
	// POST /api/v1/orders
	CreateNewOrder(ctx context.Context, req *CreateNewOrderReq) (CreateNewOrderRes, error)
	// OrderByUUID implements OrderByUUID operation.
	//
	// Returns order using uuid.
	//
	// GET /api/v1/orders/{order_uuid}
	OrderByUUID(ctx context.Context, params OrderByUUIDParams) (OrderByUUIDRes, error)
	// OrderCancel implements OrderCancel operation.
	//
	// Cancel order by uuid.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	OrderCancel(ctx context.Context, params OrderCancelParams) (OrderCancelRes, error)
	// OrderPayment implements OrderPayment operation.
	//
	// Current order payment.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	OrderPayment(ctx context.Context, req *OrderPaymentReq, params OrderPaymentParams) (OrderPaymentRes, error)
	// NewError creates *ErrRespStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrRespStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
