// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateNewOrder implements CreateNewOrder operation.
//
// Create a new order with selected details.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateNewOrder(ctx context.Context, req *CreateNewOrderReq) (r CreateNewOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderByUUID implements OrderByUUID operation.
//
// Returns order using uuid.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) OrderByUUID(ctx context.Context, params OrderByUUIDParams) (r OrderByUUIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderCancel implements OrderCancel operation.
//
// Cancel order by uuid.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) OrderCancel(ctx context.Context, params OrderCancelParams) (r OrderCancelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderPayment implements OrderPayment operation.
//
// Current order payment.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) OrderPayment(ctx context.Context, req *OrderPaymentReq, params OrderPaymentParams) (r OrderPaymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrRespStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrRespStatusCode) {
	r = new(ErrRespStatusCode)
	return r
}
