// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// OrderByUUIDParams is parameters of OrderByUUID operation.
type OrderByUUIDParams struct {
	// Uuid of the order.
	OrderUUID string
}

func unpackOrderByUUIDParams(packed middleware.Parameters) (params OrderByUUIDParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(string)
	}
	return params
}

func decodeOrderByUUIDParams(args [1]string, argsEscaped bool, r *http.Request) (params OrderByUUIDParams, _ error) {
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    36,
					MinLengthSet: true,
					MaxLength:    36,
					MaxLengthSet: true,
					Email:        false,
					Hostname:     false,
					Regex:        nil,
				}).Validate(string(params.OrderUUID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// OrderCancelParams is parameters of OrderCancel operation.
type OrderCancelParams struct {
	// Uuid of the order.
	OrderUUID string
}

func unpackOrderCancelParams(packed middleware.Parameters) (params OrderCancelParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(string)
	}
	return params
}

func decodeOrderCancelParams(args [1]string, argsEscaped bool, r *http.Request) (params OrderCancelParams, _ error) {
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    36,
					MinLengthSet: true,
					MaxLength:    36,
					MaxLengthSet: true,
					Email:        false,
					Hostname:     false,
					Regex:        nil,
				}).Validate(string(params.OrderUUID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// OrderPaymentParams is parameters of OrderPayment operation.
type OrderPaymentParams struct {
	// Uuid of the order.
	OrderUUID string
}

func unpackOrderPaymentParams(packed middleware.Parameters) (params OrderPaymentParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(string)
	}
	return params
}

func decodeOrderPaymentParams(args [1]string, argsEscaped bool, r *http.Request) (params OrderPaymentParams, _ error) {
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    36,
					MinLengthSet: true,
					MaxLength:    36,
					MaxLengthSet: true,
					Email:        false,
					Hostname:     false,
					Regex:        nil,
				}).Validate(string(params.OrderUUID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
